import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const aeonik = localFont({
  src: [
    {
      path: './fonts/Aeonik-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Aeonik_OVERVIEW-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Aeonik-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Aeonik-Black.ttf',
      weight: '900',
      style: 'normal',
    }
  ],
  variable: '--font-aeonik'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aeonik.variable} ${aeonik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
