name: zentavos-web-prod

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: production
  APP_PORT: 3002

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Install OpenVPN
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openvpn openvpn-systemd-resolved rsync
          version: 1.0
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ztv-web-build-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ztv-web-build-
            ztv-web-
      - name: Install dependencies
        run: npm ci
      - name: Build Web App
        run: npm run build
      - name: VPN config
        env:
          OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
        run: |
          echo "$OVPN_CONFIG" > client.ovpn
      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v3.1.0
        with:
          config_file: client.ovpn
          echo_config: false
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
      - name: rsync deployment
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude .git --exclude .github --exclude node_modules
          path: ./
          remote_path: ${{ secrets.DEPLOYMENT_PATH }}
          remote_host: ${{ secrets.DEPLOYMENT_HOST_PROD }}
          remote_user: ${{ secrets.DEPLOYMENT_USER_PROD }}
          remote_key: ${{ secrets.DEPLOYMENT_KEY_PROD }}
          remote_port: ${{ secrets.DEPLOYMENT_PORT }}
      - name: SSH config
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY_PROD }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem # Write the private key to a file
          chmod 600 private_key.pem # Set the appropriate permissions for the key file
      - name: Restart API service
        run: |
          ssh -i private_key.pem ${{ secrets.DEPLOYMENT_USER_PROD }}@${{ secrets.DEPLOYMENT_HOST_PROD }} -p ${{ secrets.DEPLOYMENT_PORT }} -o StrictHostKeyChecking=no <<EOF
            cd ${{ secrets.DEPLOYMENT_PATH }}
            npm install --omit=dev
            pm2 start npm --name $DEPLOYMENT_NAME -- run start
            pm2 save
          EOF
          rm -f private_key.pem # Remove the private key file after use for security
          rm -f client.ovpn # Remove ovpn file after use for security
